version: '3.8'

services:
  backend:
    build: ../task-tracker-api
    environment:
      - APP_ENV=development
    volumes:
      - ../task-tracker-api/app:/app/app
    networks:
      - app-network

  frontend:
    build: ../task-tracker-web
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
      - frontend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 